apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: redis-service
  namespace: default
spec:
  clusterServiceClassExternalName: stable.redis
  parameters:
    "cluster.slaveCount": "1"
    "master.persistence.storageClass": "standard"
    "master.resources.requests.cpu": "100m"
    "master.resources.requests.memory": "128Mi"
    "slave.resources.requests.cpu": "100m"
    "slave.resources.requests.memory": "128Mi"
